import "./globals.css";
import "@radix-ui/themes/styles.css";
import { Theme } from "@radix-ui/themes";
import "@fontsource/noto-sans-kr"; 


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`antialiased font-noto`}
      >
        <Theme>
          {children}
        </Theme>
      </body>
    </html>
  );
}
